### ISSUE TITLE
How to use dashboard variables in filtering data from CSV

### ISSUE THREAD

**Issue by jinishbshah** [grafana/grafana-csv-datasource#237]
I am trying to filter data using the dashboard variable dropdown but I need to know how can I use the variable selection in Transform to filter the data depending on that

**Comment by zoltanbedi** [comment]
Please ask questions in the community forum. https://community.grafana.com/

**Comment by DirtyOptics** [comment]
This is how many threads remain unanswered for how to create a variable using the CSV plugin.

https://community.grafana.com/t/csv-variables-in-grafana/107916
https://community.grafana.com/t/variables-csv-expansion-in-dropdown/11436
https://community.grafana.com/t/using-variables-with-csv-datasource/73648
https://community.grafana.com/t/link-csv-values-of-variables-to-make-filtrations-in-the-data-panels/80466

This in reference to Q&A questions here: 
https://github.com/grafana/grafana-csv-datasource/discussions/228

All we want is some examples of the syntax because the documentation at Grafana does not seem to work using this plugin.
I am happy to help update your doco if required? Got to get it working first.
