### ISSUE TITLE
No graphable Fields

### ISSUE THREAD

**Issue by ygutgutia** [grafana/grafana-csv-datasource#99]
I have a local .csv file of the type
time,value
2021-07-02 11:00:00, 101
2021-07-02 11:03:06, 113
2021-07-02 11:05:53, 120
2021-07-02 11:07:32, 132

When I import it in Grafana, the table view shows the data as follows:

![Screenshot (690)](https://user-images.githubusercontent.com/46281509/124229612-7fd9f800-db2b-11eb-8759-a58e16b1ed71.png)

But when I try to view it as time series, it shows No Graphable Fields. the current system time is 11:40, therefore time is not an issue.

![Screenshot (688)](https://user-images.githubusercontent.com/46281509/124229046-a3e90980-db2a-11eb-91ca-c6487ee50f23.png)

**Comment by marcusolsson** [comment]
Thanks for letting me know! Since the numbers are left-aligned in the table, I'm suspecting that they aren't detected as numbers somehow.

Could you check the Query inspector and let me know how the DataFrame structure looks like?

**Comment by ygutgutia** [comment]
Hey Thanks for the reply. The error had something to do with the Datetime format. Im sure that the above format is also acceptable  because the same data worked fine when I extracted it from a google-sheet. Anyways, I added a GMT at the end in the datetime column and it  worked for the local csv file also.

**Comment by javiBajoCero** [comment]
Exactly the same issue here.
![imagen](https://user-images.githubusercontent.com/25673527/142229170-7b0d2689-bef2-4d47-8ea5-2b0e5037aabe.png)
![imagen](https://user-images.githubusercontent.com/25673527/142229607-15f31613-44ff-4d02-9f55-781a7e7ad112.png)

I dont understand where @ygutgutia added the GMT


Im using grafana 8.2.4 in a Raspberry zero with the plugin marcusolsson-csv-datasource 0.6.1


@marcusolsson Is there a timeless way of displaying the data?
My data consists in some signals sampled each 0,5 miliseconds so a typical grafana date format is of no use to me

![imagen](https://user-images.githubusercontent.com/25673527/142232316-22938e47-0e7e-4ed1-916e-926cbae0940b.png)
My CSV file:
[https://mega.nz/file/wTwR2SAI#1WwXWsyzu-zxZpWkU6uHYhFEv1vESBkTSH_j-PbeJnk](url)
_
_
_
_
_
_
_
_
_
_
_
_
_
_
_
_
_
Edit:
it turns out the data is displayed if i use Stat visualization instead of timseries
![imagen](https://user-images.githubusercontent.com/25673527/142230760-8e9db83e-e1ae-4e84-b50c-3316ff3b1bfa.png)



okay i was the problem. This is how you define timeserie Fields
![imagen](https://user-images.githubusercontent.com/25673527/142238467-11ecea5e-2cdd-48b9-af8c-46bdab4c8246.png)
